version: "3"

services:
  choi-memo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    tty: true
    networks:
      - choiMemo-networks

networks:
  choiMemo-networks:
    external: true
